<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita94a015043d83dd17aa9648c7dab3aaf
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'Orhanerday\\OpenAi\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Orhanerday\\OpenAi\\' => 
        array (
            0 => __DIR__ . '/..' . '/orhanerday/open-ai/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita94a015043d83dd17aa9648c7dab3aaf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita94a015043d83dd17aa9648c7dab3aaf::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita94a015043d83dd17aa9648c7dab3aaf::$classMap;

        }, null, ClassLoader::class);
    }
}
